export const newOrg = {
  title: `להגיש עסק חדש`,
  form: [
    {
      element: <input />,
      name: "site_name",
      label: `שם*`,
      required: true,
      type: "text",
    },
    {
      element: <input />,
      name: "link1",
      label: `קישור1*`,
      required: true,
      type: "text",
    },
    {
      element: <input />,
      name: "link2",
      label: `קישור2`,
      required: false,
      type: "text",
    },
    {
      element: <input />,
      name: "link3",
      label: `קישור3`,
      required: false,
      type: "text",
    },
    {
      element: <input />,
      name: "facebook_link1",
      label: `קישור לפייסבוק1*`,
      required: false,
      type: "text",
    },
    {
      element: <input />,
      name: "facebook_link2",
      label: `קישור לפייסבוק2`,
      required: false,
      type: "text",
    },
    {
      element: <input />,
      name: "facebook_link3",
      label: `קישור לפייסבוק3`,
      required: false,
      type: "text",
    },
    {
      element: <input />,
      name: "instagram_link",
      label: `קישור לאינסטגרם`,
      required: true,
      type: "text",
    },
    {
      element: <input />,
      name: "linkedIn_link",
      label: `קישור ללינקדאין`,
      required: true,
      type: "text",
    },
    {
      element: <input />,
      name: "email1",
      label: `אימייל1`,
      required: false,
      type: "email1",
    },
    {
      element: <input />,
      name: "email2",
      label: `אימייל2`,
      required: false,
      type: "email",
    },
    {
      element: <input />,
      name: "tel1",
      label: `טלפון1`,
      required: false,
      type: "tel",
    },
    {
      element: <input />,
      name: "tel2",
      label: `טלפון2`,
      required: false,
      type: "tel",
    },
    {
      element: <input />,
      name: "whatsapp",
      label: `וואטסאפ`,
      required: false,
      type: "tel",
    },
  ],
};
